### ISSUE TITLE
GitHub Actions で test, linter を実行するようにすることで、開発者が安心してコードの品質を高く保てるようにする

### ISSUE THREAD

**Issue by spinute** [digitaldemocracy2030/idobata-analyst#71]
## 解決・改善したいこと

CI で test, linter を実行し、スタイルやコード品質のベースラインをキープできるようにしたい。

## 具体的な実現方法・実装方法の概要（未記入でも構いません）

- PR に対し、frontend, backend, chat-bot それぞれについて、linter を走らせ、テストを実行する GitHub Actions を定義する

**Comment by takker99** [comment]
https://github.com/digitaldemocracy2030/idobata-analyst/pull/91 がmergeされたらassignしたいと思ってます。
`npm run lint:all`を実装したので、それを使えば少々楽に書けるかなと

**Comment by takker99** [comment]
たぶんこれでいけます
```yml
name: lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: biome check
        run: npm run lint:all
```
